### ISSUE TITLE
document API to create link to a passage

### ISSUE THREAD

**Issue by droundy** [digitalbiblesociety/browserbible-3#116]
I'd love to create a link to a particular passage (or even better, several passages) of the bible.  I like that there is a button in the menu to create a link, but I'd like to be able to do this programmatically.

Even better would be to be able to create a link that shows several passages together, like:

http://bible.oremus.org/?version=NRSV&vnum=NO&passages=Genesis%201%0D%0AJames%201%0D%0AMark%201%0D%0APsalms%2081

**Comment by johndyer** [comment]
When you click on the hamburger menu, there's a URL at the bottom of the menu that will keep all the windows/passages open. If you look at the URL you'll see Bible references and window types

**Comment by droundy** [comment]
I guess this is a wont-fix closing of the bug?

**Comment by johndyer** [comment]
Maybe I'm misunderstanding. This feature already exists and it works. 

For example here's a link to see NIV and NASB for 2 Samuel:
http://biblewebapp.com/study/?w1=bible&t1=local%3AENGNIV&v1=S24_5&w2=bible&t2=local%3Aeng-NASB1995&v2=S24_5

`w1` means window 1, `v1` is the passage, and `t1` is the Bible version.

**Comment by droundy** [comment]
The issue was to document an API to programmatically generate a link to a Bible passage.  Clicking a button is not programmatic.

**Comment by alerque** [comment]
@droundy You can create these links programmatically, but the onus is on _you_ to do so. The URL interface _already is_ an API of sorts, it is a request interface to the application. There doesn't need to be an API to form a query to send to the API.
