### ISSUE TITLE
Psalm Chapter list not displaying in Brenton translation

### ISSUE THREAD

**Issue by jaydmiller** [digitalbiblesociety/browserbible-3#117]
When viewing the Brenton translation and attempting to navigate to Psalms the chapter list does not display.
![image](https://user-images.githubusercontent.com/3492192/58719276-3abbc880-839d-11e9-8e64-cfd84ab659f5.png)
The following errors are shown in the console, the highlighted errors occurred after clicking on Psalms:
![image](https://user-images.githubusercontent.com/3492192/58719408-8ff7da00-839d-11e9-8d15-2ec2466d2023.png)

**Comment by johndyer** [comment]
Unfortunately, it looks like the creator of that version didn't properly add Ps 151.
