### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by explorigin** [digitalbiblesociety/browserbible-3#74]
The http://www.inscript.org/ *About* section says that it is an open source project but there is no linked or included license.  digitalbiblesociety/browserbible includes a license file so the implication is that this would be MIT.

I'm just trying to be above reproach.

**Comment by explorigin** [comment]
Just found that this exists at both http://www.inscript.org/ and http://biblewebapp.com/study/ . The latter links to this repo, but again, no license mentioned.

**Comment by alerque** [comment]
This is a duplicate or #46. To my knowledge an actually license hasn't been specified yet.

**Comment by explorigin** [comment]
Ah right.  Sorry I missed that.
