### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by SimonBiggs** [digitalbiblesociety/browserbible-3#76]
On both mobile browser and computer browser the version currently up at http://biblewebapp.com/ (as of 15/Oct/2015) tracks away from the verse originally looked up when surrounding chapters load. Using Android Chrome and Ubuntu Chrome in each case.

**Comment by johndyer** [comment]
I think we've gotten this fixed a few times, and still have more to do as browsers changes, so I'll close thi sone.

**Comment by SimonBiggs** [comment]
Using Chrome on Android while at http://biblewebapp.com/ I can verify that this bug still occurs.
