### ISSUE TITLE
node, or npm?

### ISSUE THREAD

**Issue by githubber** [digitalbiblesociety/browserbible-3#86]
Hi!
I tried running 'node run build' under the **Build (minify)** section and received errors. I noticed that the previous steps used npm, not node. So when I tried running 'npm run build' I did get positive results.

The first resulted in:
USER:bb3-2016-03-18 USER$ sudo node build
module.js:338
    throw err;
    ^

Error: Cannot find module '/Users/USER/folder/bb3-2016-03-18/build'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

The second usage with npm resulted in:

USER:bb3-2016-03-18 USER$ sudo npm run build

> BrowserBible@3.6.5 build /Users/USER/folder/bb3-2016-03-18
> node tools/builder.js

===  SOFIA BUILDER  ====
Javascript: combine and minify: 2322ms
Warning: app/css/images/close-button.svg has already been base64 encoded in the css: 819
Warning: app/css/images/audio-ear.svg has already been base64 encoded in the css: 2781
Warning: app/css/images/arrow-down.svg has already been base64 encoded in the css: 360
Warning: app/css/images/gear.svg has already been base64 encoded in the css: 1499
Warning: app/css/images/map.svg has already been base64 encoded in the css: 1880
Warning: app/css/images/pictures.svg has already been base64 encoded in the css: 1308
Warning: app/css/images/audio-ear.svg has already been base64 encoded in the css: 2781
external URL url(//assets.bible.is/images/deaf/icon_door_intro.png)
external URL url(//assets.bible.is/images/deaf/icon_door_story.png)
external URL url(//assets.bible.is/images/deaf/icon_door_more_info.png)
external URL url(//assets.bible.is/images/deaf/icon_door_intro_active.png)
external URL url(//assets.bible.is/images/deaf/icon_door_story_active.png)
external URL url(//assets.bible.is/images/deaf/icon_door_more_info_active.png)
Warning: app/css/images/arrow-left-gray-light.svg has already been base64 encoded in the css: 1376
CSS: combine and minify: 146ms

**Comment by bennylin** [comment]
I second that
