### ISSUE TITLE
Feature request: Replace "loading" image with instructional prompt

### ISSUE THREAD

**Issue by MarcoMoreno** [digitalbiblesociety/browserbible-3#99]
The initial "loading" image is very confusing.  This spinning icon is generally regarded as a prompt to the user that the application is loading and that the user must be patient and wait.  In fact, the opposite is happening - the application is patiently waiting on the user to make a selection.

The first time I installed the app, I waited for several minutes and assumed it was performing some first-run initializations before realizing it was waiting for me to make a selection.  Others I know had a similar experience.

Therefore, I propose displaying a short instructional prompt that guides the user what to do next:
`Select a bible from the "Version" menu above`

followed by:
`Select a book and chapter from the "Reference" menu above`

Of course, these texts should be localized.

**Comment by jonBitgood** [comment]
Infinite loading while waiting on user input is not an intentional UI decision.

The problem may be that windows config option isn't initialized or that the IDs don't match the IDs for the texts you have created. If you look at lines 10-14 of the example [default config file](https://github.com/digitalbiblesociety/browserbible-3/blob/master/app/js/core/config-default.js).

`
	windows: [
		{type: 'bible', data: {textid: 'ENGNAS', fragmentid: 'JN1_1'}},
		{type: 'bible', data: {textid: 'grc_tisch', fragmentid: 'JN1_1'}},
		{type: 'search', data: {textid: 'ENGNAS', searchtext:'truth love'}}
	],
`

**Comment by MarcoMoreno** [comment]
Ahh...that was it - thanks, Jon!  The default config file references books that are not included in the initial installation.  The README wasn't clear that the config file should be adjusted regardless of whether creating a "build" version so I never bothered to look at it.

I'd love to contribute to this work and submitting a patch to provide better defaults and improve the docs is certainly within my experience level.  Hopefully I'll get a little time next week.

Seems like there should be improved error handling if the config file refers to non-existent texts.  Unfortunately, this is currently beyond my understanding.
